services:
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./conf:/etc/nginx/conf.d:ro
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    image: php:8.3-fpm
    container_name: laravel-php
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
    working_dir: /var/www/html
    command: >
      sh -c "mkdir -p storage bootstrap/cache &&
             chown -R www-data:www-data storage bootstrap/cache &&
             chmod -R ug+rw storage bootstrap/cache &&
             (php -m | grep -q pdo_mysql || docker-php-ext-install pdo pdo_mysql) &&
             php-fpm"
    networks:
      - app-network

  composer:
    image: composer:2
    container_name: laravel-composer
    working_dir: /app
    volumes:
      - ./html:/app
    command: install
    depends_on:
      - php-fpm
    networks:
      - app-network

  node:
    image: node:20
    container_name: laravel-node
    working_dir: /var/www/html
    volumes:
      - ./html:/var/www/html
    tty: true
    networks:
      - app-network      

networks:
  app-network:
    driver: bridge